def map = [
    "mumbai" : "ap-south-1",
    "seoul"  : "ap-northeast-2"
]
pipeline {
    agent any

    stages {
        stage('loop'){
            steps{
                script {
                    map.each { entry ->
                        stage (entry.key) {
                            sh """
                                echo REGION = \\\"${entry.value}\\\" >> terraform.tfvars
                                terraform -chdir=jenkins-loop init
                                terraform -chdir=jenkins-loop plan -out tfplan -input=false
                                terraform -chdir=jenkins-loop show tfplan >> tfplan.txt
                                """
                        }

                    }
                }
            }
        }
    }
}