def map = [
    "mumbai" : "ap-south-1",
    "seoul"  : "ap-northeast-2"
]
pipeline {
    agent any

    stages {
        stage('loop'){
            steps{
                echo "Running loop job"
                script {
                    map.each { entry ->
                        stage (entry.key) {
                            dir('infrastructure/ap-south-1/') {
                                sh """
                                    echo region = \\\"${entry.value}\\\" >> terraform.tfvars
                                    terraform init
                                    terraform plan -out tfplan -input=false
                                    terraform show tfplan >> tfplan.txt
                                    """
                            }
                        }
                    }
                }
            }
        }
    }
}