// def map = [
//     "mumbai" : "ap-south-1",
//     "seoul"  : "ap-northeast-2"
// ]
pipeline {
    agent any

    stages {
        stage ('Init') {
            steps {
                echo "initializing terraform"
                script {
                    dir('infrastructure/ap-south-1/') {
                        sh """
                            terraform init
                            """
                    }
                }
            }
        }
        stage ('plan') {
            steps {
                echo "terrafor paln"
                script {
                    dir('infrastructure/ap-south-1/') {
                        sh """
                            terraform plan -out tfplan -input=false
                            terraform show -no-color tfplan > tfplan.txt
                            """
                    }
                }
            }
        }
        stage ('Approval') {
            when {
                not {
                    equals expected: true, actual: params.autoApproval
                }
            }
            steps {
                script {
                    dir('infrastructure/ap-south-1') {
                        def plan = readFile 'tfplan.txt'
                        input message: "Do you want to apply the plan?",
                        parameters: [text(name: 'Plan', description: 'Please review the plan', defaultValue: plan)]
                        }
                }
            }
        }
        stage ('Apply') {
            steps {
                dir('infrastructure/ap-south-1') {
                    sh """
                        terraform apply -no-color -input=false tfplan
                }
            }
        }
    }
}